
public enum Colors {
	CHERRY, CINAMMON, RED, WINE, PLUM, EGGPLANT, GRAPE, ORCHID, PURPLE, LAVENDER, GILLYFLOWER, PINK, BABY, VIOLET, SALMON,
	TANGERINE, MELON, ORANGE, GOLD, SUNFLOWER, YELLOW, LIME, AVOCADO, LIMON, LAUREL, CHIOROPHYLL, MOSS, MINT, EMERALD, GREEN,
	POOL, PETROLEUM, SKY, TORQUOLSE, BLUE
}
